language: rust

rust:
  - stable

cache: cargo

before_script:
- export PATH=$HOME/.cargo/bin:$PATH
- mkdir -p $HOME/.config/tick
- "echo 'database_path: ~/.config/tick/test.db' > $HOME/.config/tick/config.yaml"
- cargo build
- ./target/debug/tick help
